name: Randomness Monitor

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-randomness-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # ensure the token is retained

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run the monitor script
        run: npx tsx run.ts
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the analysis script
        run: python analysis/checkBlockNumbers.py

      - name: Run checkpoint range analysis
        run: python analysis/analyze_checkpoint_range.py
      
      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add randomness-results.csv checkpoint.txt checkpoints.txt missed-blocks.csv
            git commit -m "chore: update randomness results [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
          echo "finished"
